### PR TITLE
Past hackathon update 2024

### PR DESCRIPTION
**Pull request by JihengLi**
Updated the past hackathons page: add the picture and the link of hackathon x. Updated the icon on the upper right corner.

### CODE REVIEW

**Comment by lisaliuu** [comment]
I actually think it'd be cool to leave IX's promo site in and just put X's on top of it instead of replacing IX. What do you think?

**Comment by JihengLi** [comment]
I'm not quite sure what you mean. Now the function of the site is to swipe the image left and right to see the previous site pictures. Do you mean to remove this feature and put IX's website picture under X's website picture?

**Comment by JihengLi** [comment]
Or you mean to put a new block of current hackathon on the top, then put all the past hackathons in a block below it.

**Review by lisaliuu — APPROVED** [review]
lgtm

**Pull request merged**
